"""The published numbers must still be the measured ones.

This repository's central claim is that every reported number regenerates from
a committed artifact. That was a convention: `collect_results.py` had to be
remembered after any rerun, and nothing failed if it wasn't. These tests make
it machine-enforced.

They recompute from the artifacts and compare against what is committed. They
never run an experiment, so they are fast enough for CI and cannot themselves
change a result.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
RESULTS_MD = ROOT / "docs" / "RESULTS.md"
RESULTS_JSON = ROOT / "experiments" / "results.json"


def _regenerate(tmp_path):
    """Run the collector and return what it wrote, restoring the tree after.

    The comparison below is before-against-after, so a collector that writes
    nothing passes it trivially: stubbing out `main()` with a bare `return`
    made all of these tests green. Both files are deleted first, which turns
    "wrote nothing" into a missing file rather than a silent pass.
    """
    before_md = RESULTS_MD.read_text()
    before_json = RESULTS_JSON.read_text()
    try:
        RESULTS_MD.unlink()
        RESULTS_JSON.unlink()
        subprocess.run(
            [sys.executable, str(ROOT / "experiments" / "collect_results.py")],
            check=True, capture_output=True, cwd=ROOT,
        )
        assert RESULTS_MD.exists(), (
            "collect_results.py did not write docs/RESULTS.md"
        )
        assert RESULTS_JSON.exists(), (
            "collect_results.py did not write experiments/results.json"
        )
        after_md = RESULTS_MD.read_text()
        after_json = RESULTS_JSON.read_text()
    finally:
        # the collector writes results.json and RESULTS.md at different points,
        # so a crash between them would otherwise leave one of them rewritten
        RESULTS_MD.write_text(before_md)
        RESULTS_JSON.write_text(before_json)
    return (before_md, after_md), (before_json, after_json)


def test_results_json_matches_artifacts(tmp_path):
    """results.json is what collect_results.py produces from the .npz files."""
    _, (before, after) = _regenerate(tmp_path)
    if before != after:
        b, a = json.loads(before), json.loads(after)
        drifted = {k: (b.get(k), a.get(k)) for k in set(b) | set(a) if b.get(k) != a.get(k)}
        pytest.fail(
            "results.json is stale against the committed artifacts; run "
            f"experiments/collect_results.py. Drifted: {drifted}"
        )


def test_results_md_matches_artifacts(tmp_path):
    """docs/RESULTS.md is regenerated, not hand-edited."""
    (before, after), _ = _regenerate(tmp_path)
    assert before == after, (
        "docs/RESULTS.md is stale against the committed artifacts; run "
        "experiments/collect_results.py"
    )


def _sci(v, digits):
    """Scientific notation the way the prose writes it, without a padded exponent."""
    mantissa, exponent = f"{v:.{digits}e}".split("e")
    return f"{mantissa}e{int(exponent)}"


# Numbers quoted in prose that must keep matching results.json. Each entry is
# (results.json key, formatter, [(file, context that must share the line)]).
#
# Two earlier weaknesses shaped this table. Entries that listed only
# docs/RESULTS.md were vacuous: that file is generated by the same collector
# the test above already byte-compares, so it can never disagree. And a bare
# search for the value passes on the first match anywhere in the file, so a
# nearby unrelated number satisfies it: README quotes 81 as a repeat
# measurement two lines under the 93 it is guarding. The context string pins
# each match to the sentence that is actually making the claim.
QUOTED = [
    ("E1_miss_start_m", lambda v: f"{v:.2f}", [
        ("README.md", "Miss"),
        ("docs/writeup.md", "Miss distance falls"),
        ("docs/site/experiments.md", "Miss falls from"),
    ]),
    ("CONV_order", lambda v: f"{v:.2f}", [
        ("README.md", "against the analytic"),
        ("docs/writeup.md", "converges at"),
        ("docs/site/studies.md", "on a smooth arc"),
    ]),
    ("SCALE_r2", lambda v: f"{v:.3f}", [
        ("README.md", "R² ="),
        ("docs/writeup.md", "affine in parameter count"),
        ("docs/site/studies.md", "microseconds per parameter"),
        ("docs/site/method.md", "per parameter"),
    ]),
    ("SCALE_us_per_param", lambda v: f"{v:.0f}", [
        ("README.md", "per parameter"),
        ("docs/site/studies.md", "Affine in parameter count"),
        ("docs/site/method.md", "microseconds per parameter"),
    ]),
    ("SCALE_ratio_77", lambda v: f"{v:.1f}", [
        ("docs/writeup.md", "forward solve"),
        ("docs/site/method.md", "forward solve"),
    ]),
    ("CHECKGRAD_checks", lambda v: str(int(v)), [
        ("README.md", "per gradient endpoint"),
    ]),
    ("CHECKGRAD_failures", lambda v: f"{int(v)} failures", [
        ("README.md", "per gradient endpoint"),
    ]),
    # The oracle agreements were guarded only through docs/RESULTS.md, which
    # regenerates in step with the artifact and so could never catch stale
    # prose. README states each at its own rounding.
    ("CLOSED_FORM_jacobian_worst", lambda v: _sci(v, 0),
     [("README.md", "Jacobian agreement")]),
    ("REFERENCE_jacobian_worst", lambda v: _sci(v, 0),
     [("README.md", "through the independent implementation")]),
    ("CONTACT_energy_drift", lambda v: _sci(v, 0),
     [("README.md", "drift")]),
    ("E3_saltation_spread", lambda v: f"{v:.2e}", [("docs/RESULTS.md", "saltation")]),
    ("GRAD_best_agreement", lambda v: f"{v:.2e}", [("docs/RESULTS.md", "agreement")]),
    ("REFERENCE_primal_worst", lambda v: f"{v:.3g}", [("docs/RESULTS.md", "primal")]),
    ("BENCH_ratio_eval", lambda v: f"{v:.0f}", [("docs/RESULTS.md", "ratio of medians")]),
    # These carried no guard at all. Setting point_k to 900 in the artifact
    # regenerated RESULTS.md while README, the writeup and the studies page all
    # kept publishing 983, with the suite green.
    ("ROBUST_point_correct", str, [("README.md", "independent ensembles")]),
    ("ROBUST_robust_correct", str, [("README.md", "independent ensembles")]),
    # the prose pages spell the same ratio out in words
    ("ROBUST_point_correct", lambda v: v.replace("/", " of "), [
        ("docs/writeup.md", "point design classifies"),
        ("docs/site/studies.md", "point design classifies"),
    ]),
    ("ROBUST_robust_correct", lambda v: v.replace("/", " of "), [
        ("docs/writeup.md", "ensemble design"),
        ("docs/site/studies.md", "ensemble design"),
    ]),
    ("E5B_p5_margin_ensemble", lambda v: f"{v:.2f}", [
        ("docs/site/studies.md", "ensemble-refined"),
    ]),
]


@pytest.mark.parametrize("key,fmt,sites", QUOTED)
def test_prose_quotes_current_value(key, fmt, sites):
    """A headline number in prose still matches the artifact it came from."""
    r = json.loads(RESULTS_JSON.read_text())
    assert key in r, f"{key} missing from results.json"
    wanted = fmt(r[key])
    for rel, context in sites:
        lines = (ROOT / rel).read_text().splitlines()
        # reject a digit continuation ("93" must not match "93.1" or "934"),
        # but allow a sentence-ending period after the number
        pattern = rf"(?<![\w.]){re.escape(wanted)}(?!\d)(?!\.\d)"
        # prose wraps, so the claim and its number often sit on adjacent
        # lines; a small window keeps the anchor without demanding one line
        window = 2
        hits = [
            i for i, line in enumerate(lines)
            if re.search(pattern, line)
            and any(context in near
                    for near in lines[max(0, i - window): i + window + 1])
        ]
        assert hits, (
            f"{rel} no longer quotes {key} as {wanted} near a line containing "
            f"{context!r}; either the artifact moved and the prose was not "
            "updated, the formatting changed, or the sentence was reworded"
        )


def test_every_figure_source_path_exists():
    """The figure-provenance mapping cannot point at a renamed artifact.

    The docs build enforces this too (the directive warns, and the build runs
    with -W), so this is a fast local duplicate rather than the only guard. It
    needs Sphinx, which the test job does not install.
    """
    pytest.importorskip("sphinx", reason="enforced by the docs build instead")
    sys.path.insert(0, str(ROOT / "docs" / "site" / "_ext"))
    from figure_source import SOURCES

    missing = []
    for fig, (script, artifacts) in SOURCES.items():
        for rel in [script, *artifacts]:
            if not (ROOT / rel).exists():
                missing.append(f"{fig} -> {rel}")
    assert not missing, f"figure-source mapping points at missing files: {missing}"


def test_sweep_widget_artifact_has_saltation_column():
    """The step-size widget reads a measured saltation column, not a constant."""
    import numpy as np

    rows = np.load(ROOT / "experiments" / "e3_rows.npy")
    assert rows.shape[1] >= 4, (
        "e3_rows.npy has no saltation column; the widget would fall back to "
        "printing a constant. Rerun experiments/e3_naive_vs_saltation.py"
    )
    salt = rows[:, 3]
    assert np.all(np.isfinite(salt))
    # distinct at every step size proves it was solved per dt rather than
    # copied from one solve; a tiny spread is the dt-independence claim itself
    assert len(set(salt.tolist())) > 1, (
        "saltation values repeat across step sizes, so the column was filled "
        "from one solve rather than measured at each dt"
    )
    assert float(salt.max() - salt.min()) < 1e-10, (
        "the saltation gradient is no longer dt-independent to the precision "
        "the widget and the studies page claim"
    )


def test_diffrax_claim_is_backed_by_its_artifact():
    """The comparison page's Diffrax numbers come from a committed run."""
    path = ROOT / "scripts" / "diffrax_event_gradient.json"
    assert path.exists(), "diffrax_event_gradient.json missing; run its script"
    d = json.loads(path.read_text())
    assert d["versions"]["diffrax"] and d["versions"]["jax"]
    correct = d["gradients"]["jump time closed over differentiably"]
    assert correct, "no gradients recorded for the documented usage"
    assert all(abs(g - d["expected"]) < 1e-4 for g in correct.values()), (
        "Diffrax no longer returns the exact gradient under its documented "
        "usage; docs/site/related.md says it does and must be revisited"
    )


def test_every_committed_artifact_is_documented():
    """docs/site/artifacts.md indexes every artifact, and indexes nothing else.

    The provenance page is only worth reading if it is complete. Adding an
    artifact without a row leaves a published number with no stated source,
    which is the state this repository exists to make impossible.
    """
    sys.path.insert(0, str(ROOT / "docs" / "site" / "_ext"))
    from artifact_index import ARTIFACTS

    tracked = subprocess.run(
        ["git", "ls-files", "experiments", "scripts"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout.split()
    on_disk = {p for p in tracked if p.endswith((".npz", ".npy", ".json"))}
    indexed = {a for a, _scripts, _backs in ARTIFACTS}

    assert not (on_disk - indexed), (
        f"artifacts with no row in docs/site/artifacts.md: "
        f"{sorted(on_disk - indexed)}"
    )
    assert not (indexed - on_disk), (
        f"artifacts.md lists files that are not committed: "
        f"{sorted(indexed - on_disk)}"
    )

    for artifact, scripts, _backs in ARTIFACTS:
        for rel in [artifact, *scripts]:
            assert (ROOT / rel).exists(), f"{rel} is indexed but missing"


def test_landing_page_timing_matches_the_measurement():
    """The run time on the landing page is the one time_checks.py measured.

    An earlier version of this compared results.json to timing.json and never
    touched the page, so replacing the substitution in conf.py with a literal
    would have passed. Both of the page's readers are exercised here: the
    prose substitution and the stat card.
    """
    timing = json.loads((ROOT / "experiments" / "timing.json").read_text())
    r = json.loads(RESULTS_JSON.read_text())
    measured = timing["total_median_s"]
    assert r["TIMING_checks_total_s"] == measured, (
        "results.json disagrees with timing.json; run collect_results.py"
    )

    site = ROOT / "docs" / "site"
    conf = {"__file__": str(site / "conf.py")}
    exec(compile((site / "conf.py").read_text(), "conf.py", "exec"), conf)
    substitution = conf["myst_substitutions"]["checks_walltime"]
    assert f"{measured:.0f}" in substitution, (
        f"docs/site/conf.py publishes {substitution!r}, which is not the "
        f"measured {measured} s; the page is quoting something else"
    )

    sys.path.insert(0, str(site / "_ext"))
    from stat_cards import CARDS
    assert any("TIMING_checks_total_s" in keys for keys, _fmt, _cap in CARDS), (
        "the landing page's run-time card no longer reads the timing artifact"
    )

    assert measured < 120, (
        "the four checks now take over two minutes; the landing page reads "
        "the artifact, but getting-started still promises a warm run in seconds"
    )
